package com.syndicate.permission;

public enum Permission {
    ORG_MEMBERSHIP_MANAGE,
    ORG_INVITATION_SEND,
    TRANSACTION_MEMBERSHIP_MANAGE,
    TRANSACTION_INVITATION_SEND,
    TRANSACTION_STATUS_TRANSITION,
    FACT_VERIFY_FINANCIAL,
    ISSUE_RESOLVE_LITIGATION
}
