package com.syndicate.workstream;

public enum WorkstreamType {
    TRANSACTION_READINESS,
    CORPORATE_SECRETARIAL,
    FINANCIAL_DUE_DILIGENCE,
    LEGAL_DUE_DILIGENCE,
    TAX,
    BUSINESS_DUE_DILIGENCE,
    REGULATORY_DUE_DILIGENCE,
    CAPITAL_STRUCTURE,
    MATERIAL_CONTRACTS,
    LITIGATION
}
