export const ORGANIZATION_TYPES = [
  'ISSUER',
  'MERCHANT_BANKER',
  'LEGAL_COUNSEL',
  'STATUTORY_AUDITOR',
  'CA_TAX_ADVISOR',
  'COMPANY_SECRETARY',
  'REGULATORY_CONSULTANT',
  'REGISTRAR',
  'MARKET_MAKER',
  'OTHER_ADVISOR',
];

export const ORG_ROLES = ['OWNER', 'ADMIN', 'MEMBER'];

export const COMPANY_CONSTITUTIONS = ['PRIVATE_LIMITED', 'PUBLIC_LIMITED', 'LLP', 'PARTNERSHIP', 'OPC'];

export const TRANSACTION_TYPES = ['SME_IPO'];

export const TRANSACTION_STATUSES = ['DRAFT', 'ACTIVE', 'CLOSED'];

export const TRANSACTION_ROLES = [
  'ISSUER_ADMIN',
  'PROMOTER',
  'CFO',
  'COMPANY_SECRETARY',
  'LEAD_BANKER',
  'DUE_DILIGENCE_TEAM',
  'LEAD_LAWYER',
  'LEGAL_ASSOCIATE',
  'AUDITOR',
  'TAX_ADVISOR',
  'REGULATORY_CONSULTANT',
  'ADVISOR',
];

export const WORKSTREAM_TYPES = [
  'TRANSACTION_READINESS',
  'CORPORATE_SECRETARIAL',
  'FINANCIAL_DUE_DILIGENCE',
  'LEGAL_DUE_DILIGENCE',
  'TAX',
  'BUSINESS_DUE_DILIGENCE',
  'REGULATORY_DUE_DILIGENCE',
  'CAPITAL_STRUCTURE',
  'MATERIAL_CONTRACTS',
  'LITIGATION',
];

export const EVIDENCE_DOCUMENT_TYPES = [
  'AUDITED_FINANCIAL_STATEMENT',
  'LICENCE',
  'CERTIFICATE',
  'CONTRACT',
  'BOARD_RESOLUTION',
  'GOVERNMENT_FILING',
  'PROPERTY_DOCUMENT',
  'EMAIL',
  'OTHER',
];

export const ISSUE_SEVERITIES = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'];

export const ISSUE_STATUSES = ['OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED'];

export function humanize(value) {
  if (!value) return '';
  return value
    .toLowerCase()
    .split('_')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}
