package com.syndicate.audit;

public enum AuditAction {
    FACT_CREATED,
    FACT_VERIFIED,
    FACT_SUPERSEDED,
    CANDIDATE_FACT_ACCEPTED,
    CANDIDATE_FACT_REJECTED,
    EVIDENCE_UPLOADED,
    EVIDENCE_DELETED,
    TRANSACTION_STATUS_CHANGED,
    APPROVAL_SIGNED,
    MEMBER_JOINED,
    MEMBER_REMOVED,
    CONFLICT_DETECTED,
    CONFLICT_CLEARED,
    DRHP_COMPILED,
    DRHP_INVALIDATED
}
